M48
; DRILL file {KiCad 7.0.6-0} date 2024 April 24, Wednesday 20:03:13
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-24T20:03:13-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.1413Y-1.7252
X3.1587Y-5.3776
X8.7343Y-5.3697
X8.7606Y-1.7244
T0
M30
